spring:
  application:
    name: webservice
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none        # Don't let Hibernate manage schema, use schema.sql instead
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  sql:
    init:
      platform: psql
      mode: always
      schema-locations: classpath:schema.sql
  mail:
    host: ${SPRING_EMAIL_SMTP:${EMAIL_SMTP:localhost}}
    port: ${SPRING_EMAIL_PORT:${EMAIL_PORT:25}}
    username: ${SPRING_EMAIL_USERNAME:${EMAIL_USER:}}
    password: ${SPRING_EMAIL_PASSWORD:${EMAIL_PASSWORD:}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    audience: ${AUTH0_AUDIENCE}