spring:
  application:
    name: webservice
  datasource:
    hikari:
      maximum-pool-size: 10
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none        # Don't let Hibernate manage schema, use schema.sql instead
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  mail:
    host: ${SPRING_EMAIL_SMTP}
    port: ${SPRING_EMAIL_PORT}
    username: ${SPRING_EMAIL_USER}
    password: ${SPRING_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Backend health check
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized
  health:
    mail:
      enabled: false  # Disable mail health check

okta:
  oauth2:
    issuer: "https://${AUTH0_DOMAIN}/"
    audience: ${AUTH0_AUDIENCE}

app:
  base:
    url: ${APP_BASE_URL}
