spring:
  application:
    name: webservice
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none        # Don't let Hibernate manage schema, use schema.sql instead
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  sql:
    init:
      platform: psql
      mode: always
      schema-locations: classpath:schema.sql
  mail:
    host: ${SPRING_EMAIL_SMTP}
    port: ${SPRING_EMAIL_PORT}
    username: ${SPRING_EMAIL_USERNAME}
    password: ${SPRING_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

okta:
  oauth2:
    issuer: https://dev-frns5opcuy7k1288.us.auth0.com/
    audience: http://localhost:8080